apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-leader-pv-volume
  namespace: ns-jenkins
  labels:
    location: local
    type: jenkins
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/ubuntu/k8s/jenkins/jenkins-home" # local machine path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-leader-pv-claim
  namespace: ns-jenkins
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      location: local
      type: jenkins
