apiVersion: v1
kind: PersistentVolume
metadata:
  name: front-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/home/ubuntu/k8s/frontend/conf" # local machine path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: front-pv-claim
  namespace: ns-frontend
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: local
