apiVersion: v1
kind: PersistentVolume
metadata:
  name: buildnode-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/ubuntu/dist"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildnode-pv-claim
  namespace: ns-buildnode
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
