apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtc
  namespace: ns-node
spec:
  selector:
    matchLabels:
      app: rtc
  replicas: 1
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: rtc
    spec:
      containers:
        - name: rtc
          image: wlgh325/camcoder-node:0.2
          resources:
            requests:
              cpu: 100m
              memory: 300Mi
          imagePullPolicy: Always
          ports:
            - name: node-port
              containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node-svc
  namespace: ns-node
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: node-port
  selector:
    app: rtc
